definitions:
  env_versions: &env_versions
    xcode: 15.4
  triggering:
    push: &push_event
      events:
        - push
    branch_patterns:
      - pattern: "benchmark"
        include: true
        source: true
  scripts:
    - &runBenchmarkTests
      name: Run benchmark tests
      script: sh benchmark.sh
workflows:
  ios-m1-mac-mini-workflow:
    name: iOS M1 Mac mini Workflow
    # instance_type: mac_mini_m1
    environment:
      <<: *env_versions
    triggering:
      <<: *push_event
    scripts:
      - *runBenchmarkTests
  ios-m2-mac-mini-workflow:
    name: iOS M2 Mac mini Workflow
    instance_type: mac_mini_m2
    environment:
      <<: *env_versions
    triggering:
      <<: *push_event
    scripts:
      - *runBenchmarkTests
  ios-m4-mac-mini-workflow:
    name: iOS M4 Mac mini Workflow
    environment:
      xcode: 16.2
    triggering:
      <<: *push_event
    scripts:
      - *runBenchmarkTests
  ios-m4-pro-mac-mini-workflow:
    name: iOS M4 Pro Mac mini Workflow
    environment:
      xcode: 16.1
    triggering:
      <<: *push_event
    scripts:
      - *runBenchmarkTests
  ios-m4-max-studio-workflow:
    name: iOS M4 Max Studio Workflow
    environment:
      xcode: 16.3
    triggering:
      <<: *push_event
    scripts:
      - *runBenchmarkTests
